"""empty message

Revision ID: 290fea97fea6
Revises: None
Create Date: 2014-04-27 15:13:15.635913

"""

# revision identifiers, used by Alembic.
revision = '290fea97fea6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('first_listed', sa.DateTime(), nullable=True),
    sa.Column('last_listed', sa.DateTime(), nullable=True),
    sa.Column('is_listed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('per_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('earnings', sa.Float(asdecimal=True), nullable=True),
    sa.Column('roe', sa.Float(asdecimal=True), nullable=True),
    sa.Column('book_value', sa.Float(asdecimal=True), nullable=True),
    sa.Column('pe', sa.Float(asdecimal=True), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('total_debt_ratio', sa.Float(asdecimal=True), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['detail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bal_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_ending', sa.DateTime(), nullable=True),
    sa.Column('cash_and_cash_equivalents', sa.BigInteger(), nullable=True),
    sa.Column('short_term_investments', sa.BigInteger(), nullable=True),
    sa.Column('net_receivables', sa.BigInteger(), nullable=True),
    sa.Column('inventory', sa.BigInteger(), nullable=True),
    sa.Column('other_current_assets', sa.BigInteger(), nullable=True),
    sa.Column('total_current_assets', sa.BigInteger(), nullable=True),
    sa.Column('long_term_investments', sa.BigInteger(), nullable=True),
    sa.Column('property_plant_and_equipment', sa.BigInteger(), nullable=True),
    sa.Column('goodwill', sa.BigInteger(), nullable=True),
    sa.Column('intangible_assets', sa.BigInteger(), nullable=True),
    sa.Column('accumulated_amortization', sa.BigInteger(), nullable=True),
    sa.Column('other_assets', sa.BigInteger(), nullable=True),
    sa.Column('deferred_long_term_asset_charges', sa.BigInteger(), nullable=True),
    sa.Column('total_assets', sa.BigInteger(), nullable=True),
    sa.Column('accounts_payable', sa.BigInteger(), nullable=True),
    sa.Column('short_current_long_term_debt', sa.BigInteger(), nullable=True),
    sa.Column('other_current_liabilities', sa.BigInteger(), nullable=True),
    sa.Column('total_current_liabilities', sa.BigInteger(), nullable=True),
    sa.Column('long_term_debt', sa.BigInteger(), nullable=True),
    sa.Column('other_liabilities', sa.BigInteger(), nullable=True),
    sa.Column('deferred_long_term_liability_charges', sa.BigInteger(), nullable=True),
    sa.Column('minority_interest', sa.BigInteger(), nullable=True),
    sa.Column('negative_goodwill', sa.BigInteger(), nullable=True),
    sa.Column('total_liabilities', sa.BigInteger(), nullable=True),
    sa.Column('stockholders_equity', sa.BigInteger(), nullable=True),
    sa.Column('misc_stocks_options_warrants', sa.BigInteger(), nullable=True),
    sa.Column('redeemable_preferred_stock', sa.BigInteger(), nullable=True),
    sa.Column('preferred_stock', sa.BigInteger(), nullable=True),
    sa.Column('common_stock', sa.BigInteger(), nullable=True),
    sa.Column('retained_earnings', sa.BigInteger(), nullable=True),
    sa.Column('treasury_stock', sa.BigInteger(), nullable=True),
    sa.Column('capital_surplus', sa.BigInteger(), nullable=True),
    sa.Column('other_stockholder_equity', sa.BigInteger(), nullable=True),
    sa.Column('total_stockholder_equity', sa.BigInteger(), nullable=True),
    sa.Column('net_tangible_assets', sa.BigInteger(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['detail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('close', sa.Float(asdecimal=True), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['detail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_table('bal_sheet')
    op.drop_table('per_share')
    op.drop_table('sector')
    op.drop_table('detail')
    ### end Alembic commands ###
