# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_ending', models.DateField(null=True)),
                ('cash_and_cash_equivalents', models.BigIntegerField(null=True)),
                ('short_term_investments', models.BigIntegerField(null=True)),
                ('net_receivables', models.BigIntegerField(null=True)),
                ('inventory', models.BigIntegerField(null=True)),
                ('other_current_assets', models.BigIntegerField(null=True)),
                ('total_current_assets', models.BigIntegerField(null=True)),
                ('long_term_investments', models.BigIntegerField(null=True)),
                ('property_plant_and_equipment', models.BigIntegerField(null=True)),
                ('goodwill', models.BigIntegerField(null=True)),
                ('intangible_assets', models.BigIntegerField(null=True)),
                ('accumulated_amortization', models.BigIntegerField(null=True)),
                ('other_assets', models.BigIntegerField(null=True)),
                ('deferred_long_term_asset_charges', models.BigIntegerField(null=True)),
                ('total_assets', models.BigIntegerField(null=True)),
                ('accounts_payable', models.BigIntegerField(null=True)),
                ('short_current_long_term_debt', models.BigIntegerField(null=True)),
                ('other_current_liabilities', models.BigIntegerField(null=True)),
                ('total_current_liabilities', models.BigIntegerField(null=True)),
                ('long_term_debt', models.BigIntegerField(null=True)),
                ('other_liabilities', models.BigIntegerField(null=True)),
                ('deferred_long_term_liability_charges', models.BigIntegerField(null=True)),
                ('minority_interest', models.BigIntegerField(null=True)),
                ('negative_goodwill', models.BigIntegerField(null=True)),
                ('total_liabilities', models.BigIntegerField(null=True)),
                ('stockholders_equity', models.BigIntegerField(null=True)),
                ('misc_stocks_options_warrants', models.BigIntegerField(null=True)),
                ('redeemable_preferred_stock', models.BigIntegerField(null=True)),
                ('preferred_stock', models.BigIntegerField(null=True)),
                ('common_stock', models.BigIntegerField(null=True)),
                ('retained_earnings', models.BigIntegerField(null=True)),
                ('treasury_stock', models.BigIntegerField(null=True)),
                ('capital_surplus', models.BigIntegerField(null=True)),
                ('other_stockholder_equity', models.BigIntegerField(null=True)),
                ('total_stockholder_equity', models.BigIntegerField(null=True)),
                ('net_tangible_assets', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('first_listed', models.DateField(null=True)),
                ('last_listed', models.DateField(null=True)),
                ('is_listed', models.BooleanField()),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PerShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('year', models.IntegerField()),
                ('earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('shares_outstanding', models.BigIntegerField(blank=True, null=True)),
                ('total_debt_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Detail')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.BigIntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='balsheet',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Detail'),
        ),
    ]
