# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='volume',
            field=models.BigIntegerField(null=True),
        ),
    ]
